- name: installling catalogue service 
  hosts: catalogue 
  become: yes 
  tasks: 
  - name: setting nodejs environment
    ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
