- name: installling catalogue service 
  hosts: catalogue 
  become: yes 
  tasks: 
  - name: setting nodejs environment
    ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
  - name: installing nodejs 
    ansible.builtin.yum: 
      name: nodejs
      state: installed
  - name: checking user roboshop exists or not 
    ansible.builtin.stat:
      name: roboshop
      register: output
  - name: printing output
    ansible.builtin.debug: 
      msg: " result of above task: '{{output}}'"