- name: install mongodb and run the service 
  hosts: mongodb 
  become: yes 
  tasks: 
  - name: copy mongo.repo 
    ansible.builtin.copy: 
      src: mongo.repo
      dest: /etc/yum.repo.d/mongo.repo

  - name: install mongodb
    ansible.builtin.yum:
      name: mongodb-org
      state: installed
    
